name: CI — Build & Scan

on:
    push:
        branches: [main]

jobs:
    build_and_scan:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install Trivy
              run: |
                  sudo apt-get update
                  sudo apt-get install -y wget apt-transport-https gnupg lsb-release
                  wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
                  echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee /etc/apt/sources.list.d/trivy.list
                  sudo apt-get update
                  sudo apt-get install -y trivy

            - name: Build de l'image
              run: docker build -t cyberwatch-demo:${{ github.sha }} .

            - name: Scan Trivy — rapport complet
              run: |
                  trivy image \
                    --format json \
                    --output trivy-report.json \
                    --exit-code 0 \
                    cyberwatch-demo:${{ github.sha }}

            - name: Gate sécurité — bloquer si CRITICAL ou HIGH
              run: |
                  trivy image \
                    --severity CRITICAL\
                    --exit-code 1 \
                    cyberwatch-demo:${{ github.sha }}

            - name: Upload rapport Trivy
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: trivy-report
                  path: trivy-report.json